[package]
name = "sentiric-contracts"
version = "0.4.0" # Yeni bir major versiyona geçiyoruz
edition = "2021"
description = "Provides pre-compiled Rust gRPC stubs for the Sentiric platform."
license = "MIT"
repository = "https://github.com/sentiric/sentiric-contracts"

[dependencies]
tonic = "0.11"
prost = "0.12"

[build-dependencies]
# Proto dosyalarını derlemek için build-time bağımlılığı
tonic-build = "0.11"