[package]
name = "sentiric-contracts"
# Yeni bir patch versiyonu daha oluşturacağız
version = "0.6.3" 
edition = "2021"
description = "Provides pre-compiled Rust gRPC stubs for the Sentiric platform."
license = "Apache-2.0"
repository = "https://github.com/sentiric/sentiric-contracts"

[dependencies]
# GÜNCELLENEN: tonic'in "serde" özelliğini aktive ediyoruz.
tonic = { version = "0.11", features = ["serde"] } 
prost = "0.12"
prost-types = "0.12"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
# GÜNCELLENEN: Buradan "serde" özelliğini kaldırıyoruz.
tonic-build = "0.11"