[package]
name = "sentiric-contracts"
# Yeni ve bu sefer doğru versiyon
version = "0.6.6"
edition = "2021"
description = "Provides pre-compiled Rust gRPC stubs for the Sentiric platform."
license = "Apache-2.0"
repository = "https://github.com/sentiric/sentiric-contracts"

[dependencies]
tonic = "0.11" # Serde özelliği YOK
prost = "0.12"
prost-types = "0.12" # Serde özelliği YOK
serde = { version = "1.0", features = ["derive"] }
# YENİ EKLENEN KRİTİK KÜTÜPHANE
prost-wkt-serde = "0.4.0"

[build-dependencies]
tonic-build = "0.11"