[package]
name = "sentiric-contracts"
# Temiz bir başlangıç için yeni ve doğru versiyon
version = "0.9.0"
edition = "2021"
description = "Provides pre-compiled Rust gRPC stubs for the Sentiric platform."
license = "Apache-2.0"
repository = "https://github.com/sentiric/sentiric-contracts"

[dependencies]
tonic = "0.11"
prost = "0.12"
prost-types = "0.12"
serde = { version = "1.0", features = ["derive"] }
# DOKÜMANTASYONA GÖRE DOĞRU BAĞIMLILIKLAR
prost-wkt-types = "0.6"

[build-dependencies]
tonic-build = "0.11"
# DOKÜMANTASYONA GÖRE DOĞRU BUILD BAĞIMLILIĞI
prost-wkt-build = "0.6"