[package]
name = "sentiric-contracts"
version = "0.6.5" # Versiyonu değiştirmiyoruz
edition = "2021"
description = "Provides pre-compiled Rust gRPC stubs for the Sentiric platform."
license = "Apache-2.0"
repository = "https://github.com/sentiric/sentiric-contracts"

[dependencies]
# DÜZELTİLMESİ GEREKEN SATIR BURASI: "features" kısmını tamamen kaldırıyoruz.
tonic = "0.11"
prost = "0.12"
prost-types = { version = "0.12", features = ["serde"] } # Bu satır doğru
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-build = "0.11"