[package]
name = "sentiric-contracts" # <-- BURAYI DÜZELTTİK
version = "0.3.2" # Versiyonu güncelleyelim
edition = "2021"
description = "A data-only crate holding the Protobuf definitions for the Sentiric platform."
license = "MIT"
repository = "https://github.com/sentiric/sentiric-contracts"

[lib]
path = "src/lib.rs"

[dependencies]
# Bağımlılık yok

[build-dependencies]
# Build script yok