[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sentiric-contracts"
version = "0.0.0" # Bu versiyon CI/CD tarafından otomatik güncellenecek
description = "API contracts for Sentiric microservices"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "grpcio",
    "protobuf"
]

[project.urls]
"Homepage" = "https://github.com/sentiric/sentiric-contracts"